export const C = {
  bg: "#F6F1EB",
  card: "#FFFDF9",
  cardBorder: "#E8DFD3",
  accent: "#C2785C",
  accentSoft: "#EADDD4",
  accentDark: "#9B5A3F",
  text: "#3A302A",
  textSub: "#8C7E72",
  conveyBg: "#FFF5EC",
  conveyBorder: "#F0D9C4",
  emotionBg: "#F3F0FF",
  emotionBorder: "#D8D0F0",
  emotionText: "#6B5CA5",
  pageBg: "#F9F5F0",
  panelBg: "#FFFFFF",
  panelBorder: "#E8DFD3",
  sidebar: "#FAF7F3",
  danger: "#D4564E",
  success: "#6BA368",
  hero: "#E8A838",
  heroBg: "#FFF8E8",
  heroBorder: "#F0C860",
} as const;

export const fonts = {
  display: "'Noto Serif JP','Georgia',serif",
  body: "'Noto Sans JP','Helvetica Neue',sans-serif",
  mono: "'Source Code Pro',monospace",
} as const;
